version: "3.7"
volumes:
  auth_mcsrv:

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth_mcsrv
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - auth_mcsrv:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
      - "5301:5301"