version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_NAME=auth_mcsrv
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data:
